#!/bin/bash

declare -a files=( "README.md" "install" )

contains() {
	local e
	for e in "${files[@]}"; do [[ "$e" == "$1" ]] && return 0; done
	return 1
}

DIR=`pwd`
for file in $DIR/*; do
	contains ${file##*/}
	if [[ $? == 0 ]]; then continue; fi
	ln -s $file ~/.${file##*/}
done
