#!/bin/bash

declare -a files=( "README.md" "install" )

contains() {
	local e
	for e in "${files[@]}"; do [[ "$e" == "$1" ]] && return 0; done
	return 1
}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
git --git-dir=$DIR/.git --work-tree=$DIR submodule init
git --git-dir=$DIR/.git --work-tree=$DIR submodule update

for file in $DIR/*; do
	f="${file##*/}"
	contains $f
	if [[ $? == 0 ]]; then continue; fi

	if [ -f "$HOME/.$f" ]; then type="file"; fi
	if [ -d "$HOME/.$f" ]; then type="directory"; fi
	if [ -f "$HOME/.$f" ]  || [ -d "$HOME/.$f" ]; then
		read -p " Overwrite $type .$f (y/n)? " y
		if [[ "$y" = "y" ]]; then
			echo " Wrote over $type .$f"
			ln -snf $file $HOME/.$f
		fi
	fi
done
